"""
recommendations.py — Deterministic, explainable recommendations.

Reason codes are assigned from feature thresholds defined here.
They are NEVER generated by an LLM or inferred heuristically.
Every code is traceable to a specific numeric feature value.

Language: scores are opportunity signals, not causal claims.
We say "associated with decline", not "will decline if not refreshed".

Built on the FlyRank ML Internship dataset: https://flyrank.ai
"""
from __future__ import annotations
import numpy as np
import pandas as pd

THRESHOLDS = {
    "impression_ratio_weak":  0.80,  # last/prev < 0.80 → declining momentum
    "low_avg_position":       20.0,  # avg_position > 20 → weak visibility
    "ctr_weak":                1.0,  # ctr < 1.0% (values are ×100 pct in data)
    "old_stale_age":         365,    # content_age_days > 365
    "long_since_update":     180,    # days_since_last_update > 180
    "low_log_impressions":   np.log1p(300),  # fewer than 300 impressions_90d
    "click_trend_weak":      -0.15,
    "impression_trend_weak": -0.15,
    "position_worse":         1.0,
    "high_volatility":        0.75,
}

ACTION_BANDS = [(0.75,"Refresh"),(0.50,"Review"),(0.30,"Improve"),(0.00,"Monitor")]


def _reason_starter(row: pd.Series) -> list:
    codes = []
    ratio = row.get("impression_window_ratio", 1.0)
    if ratio < THRESHOLDS["impression_ratio_weak"]:
        codes.append("STRONG_IMPRESSION_DECLINE" if ratio < 0.60 else "IMPRESSION_MOMENTUM_DOWN")
    pos = row.get("avg_position", 0.0)
    if pos > THRESHOLDS["low_avg_position"] and pos > 0:
        codes.append("WEAK_SEARCH_POSITION")
    ctr = row.get("ctr", 0.0)
    if ctr < THRESHOLDS["ctr_weak"]:
        codes.append("CTR_BELOW_1PCT")
    if (row.get("content_age_days",0) > THRESHOLDS["old_stale_age"] and
            row.get("days_since_last_update",0) > THRESHOLDS["long_since_update"]):
        codes.append("STALE_CONTENT")
    if row.get("log_impressions_90d",0) < THRESHOLDS["low_log_impressions"]:
        codes.append("LOW_VISIBILITY")
    return codes or ["GENERAL_MONITOR"]


def _reason_temporal(row: pd.Series) -> list:
    codes = []
    ct = row.get("click_trend", 0)
    if ct <= THRESHOLDS["click_trend_weak"]:
        codes.append("STRONG_CLICK_DECLINE" if ct <= -0.30 else "CLICK_TREND_WEAKENING")
    if row.get("impression_trend",0) <= THRESHOLDS["impression_trend_weak"]:
        codes.append("IMPRESSION_MOMENTUM_DOWN")
    if row.get("position_trend",0) >= THRESHOLDS["position_worse"]:
        codes.append("POSITION_DETERIORATING")
    if row.get("click_volatility",0) >= THRESHOLDS["high_volatility"]:
        codes.append("HIGH_VOLATILITY")
    return codes or ["GENERAL_MONITOR"]


def _action(score: float) -> str:
    for t, a in ACTION_BANDS:
        if score >= t:
            return a
    return "Monitor"


def generate_recommendations(features: pd.DataFrame, scores: pd.Series,
                              top_n=None, mode="starter") -> pd.DataFrame:
    """Generate ranked, explainable recommendation table.

    features : indexed by content_id (starter) or page_id (temporal)
    scores   : indexed by same ID, values in [0,1]
    mode     : "starter" or "temporal"
    """
    df = features.join(scores.rename("score"), how="inner")
    df = df.sort_values("score", ascending=False).reset_index()
    df["rank"] = np.arange(1, len(df)+1)
    fn = _reason_starter if mode == "starter" else _reason_temporal
    df["reason_codes"] = df.apply(lambda r: ", ".join(fn(r)), axis=1)
    df["action"]       = df["score"].apply(_action)
    df["score"]        = df["score"].round(4)

    # id column: could be in columns (after reset_index) or was the index name
    if "content_id" in df.columns:
        id_col = "content_id"
    elif "page_id" in df.columns:
        id_col = "page_id"
    else:
        # index name carried through reset_index
        id_col = df.columns[0]
    base   = ["rank","score","action","reason_codes"]
    s_cols = ["impression_window_ratio","avg_position","ctr","log_impressions_90d",
              "content_age_days","days_since_last_update"]
    t_cols = ["click_trend","impression_trend","ctr_trend","position_trend",
              "click_volatility","impressions_hist"]
    sigs   = [c for c in (s_cols if mode=="starter" else t_cols) if c in df.columns]
    out    = df[[id_col]+base+sigs]
    return (out.head(top_n) if top_n else out).reset_index(drop=True)
